-- Join claims to subscribers
SELECT 
  c.CLAIM_ID,
  s.FIRST_NAME,
  s.LAST_NAME,
  c.CLAIM_AMT
FROM 
  SQL_CLASS.CLAIMS c
JOIN 
  SQL_CLASS.SUBSCRIBERS s 
ON 
  c.SUBSCRIBER_NO = s.SUBSCRIBER_NO 
  AND c.MEMBER_NO = s.MEMBER_NO;

-- Join all three tables
SELECT 
  s.FIRST_NAME,
  s.LAST_NAME,
  a.CITY,
  a.STATE,
  c.CLAIM_AMT,
  c.CLAIM_DATE
FROM 
  SQL_CLASS.SUBSCRIBERS s
JOIN SQL_CLASS.ADDRESSES a 
  ON s.SUBSCRIBER_NO = a.SUBSCRIBER_NO
JOIN SQL_CLASS.CLAIMS c 
  ON s.SUBSCRIBER_NO = c.SUBSCRIBER_NO 
  AND s.MEMBER_NO = c.MEMBER_NO;
