CREATE TABLE SQL_CLASS.ADDRESSES (
  SUBSCRIBER_NO INTEGER,
  STREET VARCHAR(30),
  CITY VARCHAR(20),
  STATE CHAR(2),
  ZIP INTEGER,
  AREACODE SMALLINT,
  PHONE INTEGER
);

CREATE TABLE SQL_CLASS.SUBSCRIBERS (
  SUBSCRIBER_NO INTEGER,
  MEMBER_NO SMALLINT,
  LAST_NAME CHAR(20),
  FIRST_NAME VARCHAR(20),
  GENDER CHAR(1),
  SSN INTEGER
);

CREATE TABLE SQL_CLASS.CLAIMS (
  CLAIM_ID INTEGER,
  CLAIM_DATE DATE,
  CLAIM_SERVICE SMALLINT,
  SUBSCRIBER_NO INTEGER,
  MEMBER_NO SMALLINT,
  CLAIM_AMT DECIMAL(12,2),
  PROVIDER_NO SMALLINT
);
